# base config
# ==================================================================
debug: false
log_level: info


# 数据库配置
# ==================================================================
# 数据库
# ------------------------------------------------------------------
dbs:
  write:
    host: 127.0.0.1
    port: 5432
    dbname: crema
    username: postgres
    password: cplus123456
    maxidleconns: 4
    maxopenconns: 8
    isdebug: true
  read:
    host: 127.0.0.1
    port: 5432
    dbname: crema
    username: postgres
    password: cplus123456
    maxidleconns: 4
    maxopenconns: 8
    isdebug: true

# 客户端
gateway:
  modules:
    market: true
# ==================================================================
# 服务配置
# ==================================================================
# namespace k8s集群namespace
# -----------------------------
namespace: crema
# 服务注册与发现
# ------------------------------------------------------------------
discovery: etcd
etcds:
  - 127.0.0.1:2379


# 本地调试时需要，k8s部署时不需要此配置
# -----------------------------
services:
  Gateway:
    #discovery: p2p
    addresses:
      - 127.0.0.1:8096
    listenaddress: ":8096"

  CremaMarketService:
    #discovery: p2p
    addresses:
      - 127.0.0.1:8081
    listenaddress: ":8081"

#################################################################################################
#------------------------------------------------------------------------------------------------
cron:
  withSeconds: true
  # IfStillRunning时 delay> 0 延迟, < 0 跳过
  concurrentDelay: -1
  immediatelyRun: true
  # 分布式任务的开关
  distributedTask: false
  # 抢锁等待时间
  waitLockTime: 10s
  # etcd配置相关
  ttl: 2
  endpoints:
    - 127.0.0.1:2379
  waitlocktime: 0s

#################################################################################################
#------------------------------------------------------------------------------------------------
tvl_address:
  - tokenAPoolAddress: "FAqsr5LhMZQMYwxXrQuCH5C6bx1mVwuXG3WiQ5YjCEzk"
    tokenBPoolAddress: "DwFzRnWVxpvrrMJuQUwhBXhPhqUPMbrmDVJAt75k5ybE"
    tokenSwapAddress: "8J3avAjuRfL2CYFKKDwhhceiRoajhrHv9kN5nUiEnuBG"


#################################################################################################
#------------------------------------------------------------------------------------------------
chain_net: "main"
#################################################################################################
#------------------------------------------------------------------------------------------------
#config_center:
#  provider: "etcd"
#  host: "127.0.0.1:2379"
#  path: "/crema/config.yaml"