---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: watcher
  name: watcher
  namespace: crema
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: watcher
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2021-08-10T21:06:51+08:00'
      labels:
        app: watcher
    spec:
      containers:
        - env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image: 'harbor.cplus.link/backend/crema/watcher:latest'
          imagePullPolicy: Always
          name: service-container
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 20m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/etc/
              name: cfg
            - mountPath: /data/etc/plist/
              name: iosplist
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: cplus-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: admin
      serviceAccountName: admin
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: global-config
          name: cfg
        - configMap:
            defaultMode: 420
            name: iosplist
          name: iosplist
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: watcher
  name: watcher
  namespace: crema
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: watcher
  sessionAffinity: None
  type: ClusterIP
